import { ALL_VARS } from "./tokens";
import type { Preset, ThemeState } from "./types";

/**
 * Every variable at its library default — spread into each preset so loading
 * one enables the *complete* token set (it "supports" every variable). A token
 * set to its default renders identically to leaving it unset (the value matches
 * the `var(--rhmdp-*, default)` fallback), so this only makes the surface
 * explicit; per-preset overrides below express the palette. These are the real
 * component defaults, not the dashboard `seed` colors.
 */
const DEFAULTS: Record<string, string> = {
  /* day — base & structure */
  "--rhmdp-day-text": "inherit",
  "--rhmdp-day-muted-text": "#c7c7cc",
  "--rhmdp-day-border": "transparent",
  "--rhmdp-day-border-width": "1px",
  "--rhmdp-day-full-border-width": "0px",
  "--rhmdp-day-radius": "999px",
  "--rhmdp-day-weight": "inherit",
  "--rhmdp-day-size": "inherit",
  "--rhmdp-day-padding": "0.5rem",
  "--rhmdp-day-gap": "0px",
  /* day — state text */
  "--rhmdp-day-today-text": "#007aff",
  "--rhmdp-day-weekend-text": "#8e8e93",
  "--rhmdp-day-holiday-text": "#ff3b30",
  "--rhmdp-day-disabled-text": "#c7c7cc",
  /* day — hover / selected / range */
  "--rhmdp-day-hover-bg": "#f2f2f7",
  "--rhmdp-day-hover-text": "inherit",
  "--rhmdp-day-selected-bg": "#007aff",
  "--rhmdp-day-selected-text": "#ffffff",
  "--rhmdp-day-range-bg": "#e6f0ff",
  "--rhmdp-day-range-hover-bg": "#f2f7ff",
  /* weekday */
  "--rhmdp-weekday-text": "inherit",
  "--rhmdp-weekday-weight": "600",
  "--rhmdp-weekday-size": "inherit",
  /* title */
  "--rhmdp-title-text": "inherit",
  "--rhmdp-title-weight": "600",
  "--rhmdp-title-size": "1.5rem",
  /* header month/year <select> dropdowns */
  "--rhmdp-header-select-bg": "transparent",
  "--rhmdp-header-select-text": "inherit",
  "--rhmdp-header-select-border": "transparent",
  "--rhmdp-header-select-radius": "revert",
  "--rhmdp-header-select-padding": "revert",
  "--rhmdp-header-select-size": "revert",
  /* arrow buttons (Header / PanelHeader / TimePicker) */
  "--rhmdp-arrow-text": "inherit",
  "--rhmdp-arrow-bg": "transparent",
  "--rhmdp-arrow-hover-bg": "#f2f2f7",
  "--rhmdp-arrow-hover-text": "inherit",
  /* header label weight */
  "--rhmdp-header-weight": "600",
  /* time */
  "--rhmdp-time-text": "inherit",
  "--rhmdp-time-weight": "600",
  "--rhmdp-time-size": "1.25rem",
  /* panel */
  "--rhmdp-panel-selected-bg": "#007aff",
  "--rhmdp-panel-selected-text": "#ffffff",
  "--rhmdp-panel-cell-bg": "transparent",
  "--rhmdp-panel-cell-text": "inherit",
  "--rhmdp-panel-cell-hover-bg": "#f2f2f7",
  "--rhmdp-panel-cell-hover-text": "inherit",
  "--rhmdp-panel-cell-size": "inherit",
  "--rhmdp-panel-cell-weight": "inherit",
};

/**
 * Ready-made palettes lifted from the `Beautiful Themes` story gallery. Each
 * spreads `DEFAULTS` and overrides what it cares about, so loading one emits the
 * full token set. Where the original used a CSS gradient for the selected day
 * (which a single token can't express), we approximate it with a solid color.
 */
export const PRESETS: Preset[] = [
  {
    name: "Aurora Glass",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#ffffff",
      "--rhmdp-day-muted-text": "rgba(255,255,255,0.45)",
      "--rhmdp-day-selected-bg": "#7c3aed",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "rgba(255,255,255,0.18)",
      "--rhmdp-day-range-hover-bg": "rgba(255,255,255,0.10)",
      "--rhmdp-day-hover-bg": "rgba(255,255,255,0.18)",
      "--rhmdp-day-hover-text": "#ffffff",
      "--rhmdp-day-today-text": "#ffffff",
      "--rhmdp-day-weekend-text": "rgba(255,255,255,0.6)",
      "--rhmdp-day-holiday-text": "#ffd1dc",
      "--rhmdp-day-disabled-text": "rgba(255,255,255,0.3)",
      "--rhmdp-weekday-text": "rgba(255,255,255,0.75)",
      "--rhmdp-title-text": "#ffffff",
      "--rhmdp-arrow-text": "#ffffff",
      "--rhmdp-arrow-hover-bg": "rgba(255,255,255,0.25)",
      "--rhmdp-arrow-hover-text": "#ffffff",
      "--rhmdp-header-select-bg": "rgba(255,255,255,0.2)",
      "--rhmdp-header-select-text": "#ffffff",
      "--rhmdp-header-select-border": "rgba(255,255,255,0.3)",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#ffffff",
      "--rhmdp-panel-selected-bg": "#7c3aed",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#ffffff",
      "--rhmdp-panel-cell-hover-bg": "rgba(255,255,255,0.18)",
      "--rhmdp-panel-cell-hover-text": "#ffffff",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "0.95rem",
      "--rhmdp-weekday-weight": "600",
      "--rhmdp-weekday-size": "0.72rem",
      "--rhmdp-title-weight": "600",
      "--rhmdp-title-size": "1.4rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "600",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: {
        background:
          "linear-gradient(135deg, #6d83f2 0%, #a06bf0 50%, #f17bb4 100%)",
      },
      card: {
        background: "rgba(255, 255, 255, 0.18)",
        backdropFilter: "blur(18px)",
        WebkitBackdropFilter: "blur(18px)",
        border: "1px solid rgba(255, 255, 255, 0.35)",
        boxShadow: "0 20px 50px rgba(80, 40, 140, 0.35)",
      },
    },
  },
  {
    name: "Midnight Neon",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "10px",
      "--rhmdp-day-text": "#cbd5e1",
      "--rhmdp-day-muted-text": "#475569",
      "--rhmdp-day-selected-bg": "#22d3ee",
      "--rhmdp-day-selected-text": "#06141b",
      "--rhmdp-day-range-bg": "rgba(34,211,238,0.18)",
      "--rhmdp-day-range-hover-bg": "rgba(34,211,238,0.10)",
      "--rhmdp-day-hover-bg": "#1c2740",
      "--rhmdp-day-hover-text": "#67e8f9",
      "--rhmdp-day-today-text": "#67e8f9",
      "--rhmdp-day-weekend-text": "#f472b6",
      "--rhmdp-day-holiday-text": "#fb7185",
      "--rhmdp-day-disabled-text": "#475569",
      "--rhmdp-weekday-text": "#64748b",
      "--rhmdp-title-text": "#f8fafc",
      "--rhmdp-arrow-text": "#22d3ee",
      "--rhmdp-arrow-hover-bg": "#1c2740",
      "--rhmdp-arrow-hover-text": "#67e8f9",
      "--rhmdp-header-select-bg": "#1a2234",
      "--rhmdp-header-select-text": "#cbd5e1",
      "--rhmdp-header-select-border": "#243049",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#f8fafc",
      "--rhmdp-panel-selected-bg": "#22d3ee",
      "--rhmdp-panel-selected-text": "#06141b",
      "--rhmdp-panel-cell-text": "#cbd5e1",
      "--rhmdp-panel-cell-hover-bg": "#1c2740",
      "--rhmdp-panel-cell-hover-text": "#67e8f9",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "0.95rem",
      "--rhmdp-weekday-weight": "700",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "700",
      "--rhmdp-title-size": "1.35rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "700",
      "--rhmdp-time-size": "1.3rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: {
        background:
          "radial-gradient(circle at 30% 20%, #1b2735 0%, #090a0f 70%)",
      },
      card: {
        background: "#101522",
        border: "1px solid #1f2a3d",
        boxShadow: "0 24px 60px rgba(0,0,0,0.6)",
      },
    },
  },
  {
    name: "Sunset Peach",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#7c2d12",
      "--rhmdp-day-muted-text": "#e7b6a0",
      "--rhmdp-day-selected-bg": "#fb923c",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#ffe4d1",
      "--rhmdp-day-range-hover-bg": "#fff0e6",
      "--rhmdp-day-hover-bg": "#ffe3d0",
      "--rhmdp-day-hover-text": "#7c2d12",
      "--rhmdp-day-today-text": "#ea580c",
      "--rhmdp-day-weekend-text": "#fb7185",
      "--rhmdp-day-holiday-text": "#f43f5e",
      "--rhmdp-day-disabled-text": "#deb6a3",
      "--rhmdp-weekday-text": "#c2754b",
      "--rhmdp-title-text": "#9a3412",
      "--rhmdp-arrow-text": "#ea580c",
      "--rhmdp-arrow-hover-bg": "#ffe3d0",
      "--rhmdp-arrow-hover-text": "#9a3412",
      "--rhmdp-header-select-bg": "#fff1e7",
      "--rhmdp-header-select-text": "#9a3412",
      "--rhmdp-header-select-border": "#ffd8bf",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#9a3412",
      "--rhmdp-panel-selected-bg": "#fb923c",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#7c2d12",
      "--rhmdp-panel-cell-hover-bg": "#ffe3d0",
      "--rhmdp-panel-cell-hover-text": "#9a3412",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "1rem",
      "--rhmdp-weekday-weight": "600",
      "--rhmdp-weekday-size": "0.72rem",
      "--rhmdp-title-weight": "700",
      "--rhmdp-title-size": "1.5rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "600",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: { background: "linear-gradient(135deg, #ffd1a1 0%, #ff9a9e 100%)" },
      card: {
        background: "#fffaf6",
        boxShadow: "0 18px 40px rgba(255, 122, 95, 0.3)",
      },
    },
  },
  {
    name: "Minimal Mono",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#333333",
      "--rhmdp-day-muted-text": "#cfcfcf",
      "--rhmdp-day-selected-bg": "#111111",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#ececec",
      "--rhmdp-day-range-hover-bg": "#f5f5f5",
      "--rhmdp-day-hover-bg": "#f0f0f0",
      "--rhmdp-day-hover-text": "#111111",
      "--rhmdp-day-today-text": "#111111",
      "--rhmdp-day-weekend-text": "#bcbcbc",
      "--rhmdp-day-holiday-text": "#999999",
      "--rhmdp-day-disabled-text": "#cfcfcf",
      "--rhmdp-weekday-text": "#bbbbbb",
      "--rhmdp-title-text": "#111111",
      "--rhmdp-arrow-text": "#111111",
      "--rhmdp-arrow-hover-bg": "#f0f0f0",
      "--rhmdp-arrow-hover-text": "#111111",
      "--rhmdp-header-select-text": "#111111",
      "--rhmdp-header-weight": "300",
      "--rhmdp-time-text": "#111111",
      "--rhmdp-panel-selected-bg": "#111111",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#333333",
      "--rhmdp-panel-cell-hover-bg": "#f0f0f0",
      "--rhmdp-panel-cell-hover-text": "#111111",
      "--rhmdp-day-weight": "300",
      "--rhmdp-day-size": "1rem",
      "--rhmdp-weekday-weight": "400",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "300",
      "--rhmdp-time-weight": "300",
      "--rhmdp-panel-cell-weight": "300",
    },
    preview: {
      page: { background: "#fafafa" },
      card: {
        background: "#fff",
        border: "1px solid #ececec",
        boxShadow: "0 8px 30px rgba(0,0,0,0.05)",
      },
    },
  },
  {
    name: "Mint Fresh",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#0f5d57",
      "--rhmdp-day-muted-text": "#9cd3c8",
      "--rhmdp-day-selected-bg": "#14b8a6",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#d1fae5",
      "--rhmdp-day-range-hover-bg": "#ecfdf5",
      "--rhmdp-day-hover-bg": "#d6f7e7",
      "--rhmdp-day-hover-text": "#0f5d57",
      "--rhmdp-day-today-text": "#14b8a6",
      "--rhmdp-day-weekend-text": "#f59e0b",
      "--rhmdp-day-holiday-text": "#f43f5e",
      "--rhmdp-day-disabled-text": "#9cd3c8",
      "--rhmdp-weekday-text": "#5eada2",
      "--rhmdp-title-text": "#0f766e",
      "--rhmdp-arrow-text": "#14b8a6",
      "--rhmdp-arrow-hover-bg": "#d6f7e7",
      "--rhmdp-arrow-hover-text": "#0f766e",
      "--rhmdp-header-select-bg": "#ecfdf5",
      "--rhmdp-header-select-text": "#0f766e",
      "--rhmdp-header-select-border": "#b7ebdd",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#0f766e",
      "--rhmdp-panel-selected-bg": "#14b8a6",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#0f5d57",
      "--rhmdp-panel-cell-hover-bg": "#d6f7e7",
      "--rhmdp-panel-cell-hover-text": "#0f766e",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "0.95rem",
      "--rhmdp-weekday-weight": "600",
      "--rhmdp-weekday-size": "0.72rem",
      "--rhmdp-title-weight": "700",
      "--rhmdp-title-size": "1.45rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "600",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: { background: "linear-gradient(135deg, #d3f8e2 0%, #a1e3d8 100%)" },
      card: {
        background: "#ffffff",
        boxShadow: "0 16px 40px rgba(16, 122, 110, 0.22)",
      },
    },
  },
  {
    name: "Royal Gold",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "10px",
      "--rhmdp-day-text": "#e0e7ff",
      "--rhmdp-day-muted-text": "#6d6aa8",
      "--rhmdp-day-selected-bg": "#fbbf24",
      "--rhmdp-day-selected-text": "#1e1b4b",
      "--rhmdp-day-range-bg": "#312e81",
      "--rhmdp-day-range-hover-bg": "#3730a3",
      "--rhmdp-day-hover-bg": "#2d2a66",
      "--rhmdp-day-hover-text": "#fde68a",
      "--rhmdp-day-today-text": "#fbbf24",
      "--rhmdp-day-weekend-text": "#818cf8",
      "--rhmdp-day-holiday-text": "#fca5a5",
      "--rhmdp-day-disabled-text": "#6d6aa8",
      "--rhmdp-weekday-text": "#a5b4fc",
      "--rhmdp-title-text": "#fde68a",
      "--rhmdp-arrow-text": "#fbbf24",
      "--rhmdp-arrow-hover-bg": "#2d2a66",
      "--rhmdp-arrow-hover-text": "#fde68a",
      "--rhmdp-header-select-bg": "#312e81",
      "--rhmdp-header-select-text": "#e0e7ff",
      "--rhmdp-header-select-border": "#4338ca",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#fde68a",
      "--rhmdp-panel-selected-bg": "#fbbf24",
      "--rhmdp-panel-selected-text": "#1e1b4b",
      "--rhmdp-panel-cell-text": "#e0e7ff",
      "--rhmdp-panel-cell-hover-bg": "#2d2a66",
      "--rhmdp-panel-cell-hover-text": "#fde68a",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "0.95rem",
      "--rhmdp-weekday-weight": "600",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "600",
      "--rhmdp-title-size": "1.6rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "600",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: { background: "linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)" },
      card: {
        background: "#1e1b4b",
        border: "1px solid #3730a3",
        boxShadow: "0 24px 60px rgba(0,0,0,0.5)",
      },
    },
  },
  {
    name: "Crimson Grid",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "0px",
      "--rhmdp-day-border": "#c7cbcf",
      "--rhmdp-day-full-border-width": "1px",
      "--rhmdp-day-gap": "2px",
      "--rhmdp-day-selected-bg": "#d80202",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#ff9a9a",
      "--rhmdp-day-range-hover-bg": "#ffd0d0",
      "--rhmdp-day-hover-bg": "#ffe3e3",
      "--rhmdp-day-hover-text": "#111111",
      "--rhmdp-day-today-text": "#d80202",
      "--rhmdp-day-weekend-text": "#cf4d4d",
      "--rhmdp-day-holiday-text": "#b91c1c",
      "--rhmdp-day-disabled-text": "#bbbbbb",
      "--rhmdp-weekday-text": "#7a7a7a",
      "--rhmdp-arrow-hover-bg": "#ffe3e3",
      "--rhmdp-arrow-hover-text": "#d80202",
      "--rhmdp-header-select-bg": "#f0f0f0",
      "--rhmdp-header-select-text": "#000000",
      "--rhmdp-header-select-border": "#c7cbcf",
      "--rhmdp-header-select-radius": "5px",
      "--rhmdp-header-select-padding": "4px",
      "--rhmdp-time-text": "#111111",
      "--rhmdp-panel-selected-bg": "#d80202",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-hover-bg": "#ffe3e3",
      "--rhmdp-panel-cell-hover-text": "#d80202",
      "--rhmdp-day-weight": "400",
      "--rhmdp-day-size": "0.9rem",
      "--rhmdp-weekday-weight": "700",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "700",
      "--rhmdp-title-size": "1.3rem",
      "--rhmdp-header-weight": "700",
      "--rhmdp-time-weight": "600",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "600",
    },
  },
  {
    name: "Lime Sheet",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "0px",
      "--rhmdp-day-border": "#d6dadf",
      "--rhmdp-day-text": "#494949",
      "--rhmdp-day-selected-bg": "#a4fc00",
      "--rhmdp-day-selected-text": "#1a2e05",
      "--rhmdp-day-range-bg": "#e7ffb9",
      "--rhmdp-day-range-hover-bg": "#ecf8d5",
      "--rhmdp-day-hover-bg": "#eef7d2",
      "--rhmdp-day-hover-text": "#1a2e05",
      "--rhmdp-day-today-text": "#65a30d",
      "--rhmdp-day-weekend-text": "#ff0000",
      "--rhmdp-day-holiday-text": "#dc2626",
      "--rhmdp-day-disabled-text": "#bcbcbc",
      "--rhmdp-weekday-text": "#7a7a7a",
      "--rhmdp-title-text": "#5c5c5c",
      "--rhmdp-arrow-hover-bg": "#eef7d2",
      "--rhmdp-arrow-hover-text": "#5c5c5c",
      "--rhmdp-header-select-bg": "#f0f0f0",
      "--rhmdp-header-select-text": "#000000",
      "--rhmdp-header-select-radius": "5px",
      "--rhmdp-header-select-padding": "4px",
      "--rhmdp-time-text": "#5c5c5c",
      "--rhmdp-panel-selected-bg": "#a4fc00",
      "--rhmdp-panel-selected-text": "#1a2e05",
      "--rhmdp-panel-cell-text": "#494949",
      "--rhmdp-panel-cell-hover-bg": "#eef7d2",
      "--rhmdp-panel-cell-hover-text": "#5c5c5c",
      // Thin, wide-tracked type — the airy opposite of Crimson's bold grid.
      "--rhmdp-day-weight": "400",
      "--rhmdp-day-size": "0.9rem",
      "--rhmdp-weekday-weight": "500",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "200",
      "--rhmdp-title-size": "1.25rem",
      "--rhmdp-header-weight": "400",
      "--rhmdp-time-weight": "400",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "400",
    },
  },
  {
    name: "iOS Cupertino",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#1c1c1e",
      "--rhmdp-day-muted-text": "#c7c7cc",
      "--rhmdp-day-selected-bg": "#ff3b30",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#ffe5e3",
      "--rhmdp-day-range-hover-bg": "#fff0ef",
      "--rhmdp-day-hover-bg": "#f2f2f7",
      "--rhmdp-day-hover-text": "#1c1c1e",
      "--rhmdp-day-today-text": "#ff3b30",
      "--rhmdp-day-weekend-text": "#8e8e93",
      "--rhmdp-day-holiday-text": "#ff3b30",
      "--rhmdp-day-disabled-text": "#c7c7cc",
      "--rhmdp-weekday-text": "#8e8e93",
      "--rhmdp-title-text": "#1c1c1e",
      "--rhmdp-arrow-text": "#ff3b30",
      "--rhmdp-arrow-hover-bg": "#f2f2f7",
      "--rhmdp-arrow-hover-text": "#ff3b30",
      "--rhmdp-header-select-bg": "#f2f2f7",
      "--rhmdp-header-select-text": "#1c1c1e",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#1c1c1e",
      "--rhmdp-panel-selected-bg": "#ff3b30",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#1c1c1e",
      "--rhmdp-panel-cell-hover-bg": "#f2f2f7",
      "--rhmdp-panel-cell-hover-text": "#ff3b30",
      "--rhmdp-day-weight": "400",
      "--rhmdp-day-size": "1.05rem",
      "--rhmdp-weekday-weight": "600",
      "--rhmdp-weekday-size": "0.7rem",
      "--rhmdp-title-weight": "600",
      "--rhmdp-title-size": "1.3rem",
      "--rhmdp-header-weight": "600",
      "--rhmdp-time-weight": "500",
      "--rhmdp-time-size": "1.2rem",
      "--rhmdp-panel-cell-weight": "400",
    },
    preview: {
      page: { background: "#f2f2f7" },
      card: {
        background: "#ffffff",
        borderRadius: 16,
        border: "1px solid #e5e5ea",
        boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
      },
    },
  },
  {
    name: "Android Material You",
    tokens: {
      ...DEFAULTS,
      "--rhmdp-day-radius": "999px",
      "--rhmdp-day-text": "#1c1b1f",
      "--rhmdp-day-muted-text": "#c4c0c9",
      "--rhmdp-day-selected-bg": "#6750a4",
      "--rhmdp-day-selected-text": "#ffffff",
      "--rhmdp-day-range-bg": "#e8def8",
      "--rhmdp-day-range-hover-bg": "#f3edf7",
      "--rhmdp-day-hover-bg": "#ece6f4",
      "--rhmdp-day-hover-text": "#21005d",
      "--rhmdp-day-today-text": "#6750a4",
      "--rhmdp-day-weekend-text": "#49454f",
      "--rhmdp-day-holiday-text": "#b3261e",
      "--rhmdp-day-disabled-text": "#c4c0c9",
      "--rhmdp-weekday-text": "#49454f",
      "--rhmdp-title-text": "#1c1b1f",
      "--rhmdp-arrow-text": "#49454f",
      "--rhmdp-arrow-hover-bg": "#ece6f4",
      "--rhmdp-arrow-hover-text": "#6750a4",
      "--rhmdp-header-select-bg": "#f3edf7",
      "--rhmdp-header-select-text": "#1c1b1f",
      "--rhmdp-header-select-border": "#cac4d0",
      "--rhmdp-header-select-radius": "8px",
      "--rhmdp-header-select-padding": "4px 6px",
      "--rhmdp-time-text": "#1c1b1f",
      "--rhmdp-panel-selected-bg": "#6750a4",
      "--rhmdp-panel-selected-text": "#ffffff",
      "--rhmdp-panel-cell-text": "#1c1b1f",
      "--rhmdp-panel-cell-hover-bg": "#ece6f4",
      "--rhmdp-panel-cell-hover-text": "#21005d",
      "--rhmdp-day-weight": "500",
      "--rhmdp-day-size": "1rem",
      "--rhmdp-weekday-weight": "500",
      "--rhmdp-weekday-size": "0.75rem",
      "--rhmdp-title-weight": "500",
      "--rhmdp-title-size": "1.375rem",
      "--rhmdp-header-weight": "500",
      "--rhmdp-time-weight": "500",
      "--rhmdp-time-size": "1.25rem",
      "--rhmdp-panel-cell-weight": "500",
    },
    preview: {
      page: { background: "#e7e0ec" },
      card: {
        background: "#fffbfe",
        borderRadius: 28,
        boxShadow: "0 12px 32px rgba(103, 80, 164, 0.22)",
      },
    },
  },
];

/**
 * Build a full theme state from a preset: tokens the preset defines are enabled
 * with its value; every other token is reset to its seed and disabled, so it
 * falls back to the library default.
 */
export const stateFromPreset = (preset: Preset): ThemeState =>
  Object.fromEntries(
    ALL_VARS.map((v) => {
      const value = preset.tokens[v.cssVar];
      return [
        v.cssVar,
        value != null
          ? { value, enabled: true }
          : { value: v.seed, enabled: false },
      ];
    })
  );
