import type { Section, ThemeState, VarDef } from "./types";

/**
 * Every themeable token, grouped the same way the README documents them. The
 * `seed` / `enabledByDefault` values mirror the library defaults: tokens that
 * default to `inherit`/`transparent` start disabled so the picker matches the
 * stock look until you opt in.
 */
export const SECTIONS: Section[] = [
  {
    title: "Base",
    vars: [
      {
        cssVar: "--rhmdp-day-text",
        label: "Day text",
        hint: "base day number color",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-day-muted-text",
        label: "Muted text",
        hint: "other-month days",
        kind: "color",
        seed: "#c7c7cc",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-border",
        label: "Cell border",
        hint: "day cell border color",
        kind: "color",
        seed: "#e5e7eb",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-day-border-width",
        label: "Border width",
        hint: "normal (shared) cell border width",
        kind: "length",
        seed: "1px",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-day-full-border-width",
        label: "Full cell border",
        hint: "border width on all 4 sides (0 = shared)",
        kind: "length",
        seed: "1px",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-day-radius",
        label: "Corner radius",
        hint: "day cell + range-end radius",
        kind: "length",
        seed: "999px",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-padding",
        label: "Day padding",
        hint: "padding inside each day cell",
        kind: "length",
        seed: "0.5rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-day-gap",
        label: "Day grid gap",
        hint: "gap between day cells (0 = shared borders)",
        kind: "length",
        seed: "0px",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Selection",
    vars: [
      {
        cssVar: "--rhmdp-day-selected-bg",
        label: "Selected bg",
        hint: "selected day background",
        kind: "color",
        seed: "#007aff",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-selected-text",
        label: "Selected text",
        hint: "selected day text",
        kind: "color",
        seed: "#ffffff",
        enabledByDefault: true,
      },
    ],
  },
  {
    title: "Range",
    vars: [
      {
        cssVar: "--rhmdp-day-range-bg",
        label: "In-range bg",
        hint: "days inside the selected range",
        kind: "color",
        seed: "#e6f0ff",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-range-hover-bg",
        label: "Hover-range bg",
        hint: "days in the hovered-range preview",
        kind: "color",
        seed: "#f2f7ff",
        enabledByDefault: true,
      },
    ],
  },
  {
    title: "States",
    vars: [
      {
        cssVar: "--rhmdp-day-today-text",
        label: "Today text",
        hint: "today's number",
        kind: "color",
        seed: "#007aff",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-weekend-text",
        label: "Weekend text",
        hint: "weekday marked as weekend",
        kind: "color",
        seed: "#8e8e93",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-holiday-text",
        label: "Holiday text",
        hint: "day marked as holiday",
        kind: "color",
        seed: "#ff3b30",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-disabled-text",
        label: "Disabled text",
        hint: "disabled day text",
        kind: "color",
        seed: "#c7c7cc",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-hover-bg",
        label: "Day hover bg",
        hint: "hover background on selectable days",
        kind: "color",
        seed: "#f2f2f7",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-day-hover-text",
        label: "Day hover text",
        hint: "hover text on selectable days",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Components",
    vars: [
      {
        cssVar: "--rhmdp-weekday-text",
        label: "Weekday header",
        hint: "WeekDays header text",
        kind: "color",
        seed: "#6b7280",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-title-text",
        label: "Title text",
        hint: "Title text",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-bg",
        label: "Select bg",
        hint: "Header month/year dropdown background",
        kind: "color",
        seed: "#ffffff",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-text",
        label: "Select text",
        hint: "Header month/year dropdown text",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-border",
        label: "Select border",
        hint: "Header month/year dropdown border",
        kind: "color",
        seed: "#d1d5db",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-radius",
        label: "Select radius",
        hint: "Header month/year dropdown corner radius",
        kind: "length",
        seed: "5px",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-padding",
        label: "Select padding",
        hint: "Header month/year dropdown padding",
        kind: "length",
        seed: "5px",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-arrow-text",
        label: "Arrow color",
        hint: "Header / PanelHeader / TimePicker arrow color",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-arrow-bg",
        label: "Arrow bg",
        hint: "arrow button background (Header / PanelHeader / TimePicker)",
        kind: "color",
        seed: "#ffffff",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-arrow-hover-bg",
        label: "Arrow hover bg",
        hint: "arrow button hover bg (Header / PanelHeader / TimePicker)",
        kind: "color",
        seed: "#f2f2f7",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-arrow-hover-text",
        label: "Arrow hover color",
        hint: "arrow button hover color (Header / PanelHeader / TimePicker)",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-time-text",
        label: "Time text",
        hint: "TimePicker value text",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Panel header",
    vars: [
      {
        cssVar: "--rhmdp-panel-selected-bg",
        label: "Panel selected bg",
        hint: "selected month/year cell",
        kind: "color",
        seed: "#007aff",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-panel-selected-text",
        label: "Panel selected text",
        hint: "selected month/year cell text",
        kind: "color",
        seed: "#ffffff",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-panel-cell-bg",
        label: "Cell bg",
        hint: "month/year cell background",
        kind: "color",
        seed: "#ffffff",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-panel-cell-text",
        label: "Cell text",
        hint: "month/year cell text",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-panel-cell-hover-bg",
        label: "Cell hover bg",
        hint: "month/year cell hover background",
        kind: "color",
        seed: "#f2f2f7",
        enabledByDefault: true,
      },
      {
        cssVar: "--rhmdp-panel-cell-hover-text",
        label: "Cell hover text",
        hint: "month/year cell hover text",
        kind: "color",
        seed: "#111827",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-panel-cell-size",
        label: "Cell size",
        hint: "month/year cell font size",
        kind: "size",
        seed: "1rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-panel-cell-weight",
        label: "Cell weight",
        hint: "month/year cell font weight",
        kind: "weight",
        seed: "400",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Font weight",
    vars: [
      {
        cssVar: "--rhmdp-day-weight",
        label: "Day weight",
        hint: "day number font weight",
        kind: "weight",
        seed: "400",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-weekday-weight",
        label: "Weekday weight",
        hint: "WeekDays header font weight",
        kind: "weight",
        seed: "700",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-title-weight",
        label: "Title weight",
        hint: "Title font weight",
        kind: "weight",
        seed: "700",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-weight",
        label: "Header weight",
        hint: "Header / PanelHeader month-year label weight",
        kind: "weight",
        seed: "700",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-time-weight",
        label: "Time weight",
        hint: "TimePicker value font weight",
        kind: "weight",
        seed: "700",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Font family",
    vars: [
      {
        cssVar: "--rhmdp-font-family",
        label: "Font family",
        hint: "calendar font (defaults to inheriting the host app's)",
        kind: "font",
        seed: "-apple-system, BlinkMacSystemFont, system-ui, sans-serif",
        enabledByDefault: false,
      },
    ],
  },
  {
    title: "Font size",
    vars: [
      {
        cssVar: "--rhmdp-day-size",
        label: "Day size",
        hint: "day number font size",
        kind: "size",
        seed: "1rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-weekday-size",
        label: "Weekday size",
        hint: "WeekDays header font size",
        kind: "size",
        seed: "0.875rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-title-size",
        label: "Title size",
        hint: "Title font size",
        kind: "size",
        seed: "1.5rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-time-size",
        label: "Time size",
        hint: "TimePicker value font size",
        kind: "size",
        seed: "1.25rem",
        enabledByDefault: false,
      },
      {
        cssVar: "--rhmdp-header-select-size",
        label: "Select size",
        hint: "Header month/year dropdown font size",
        kind: "size",
        seed: "0.875rem",
        enabledByDefault: false,
      },
    ],
  },
];

/** Flat list of every themeable token across all sections. */
export const ALL_VARS: VarDef[] = SECTIONS.flatMap((s) => s.vars);

/** The builder's starting state — each token at its seed / default-enabled flag. */
export const initialState: ThemeState = Object.fromEntries(
  ALL_VARS.map((v) => [
    v.cssVar,
    { value: v.seed, enabled: v.enabledByDefault },
  ])
);
