name: Vitest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Vitest
        run: yarn test

      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: vitest-results
      #     path: vitest-results.xml
